import { getAssetPath } from '@stencil/core';

export const CONSTANTS = {
  videoSrc1: getAssetPath('../../assets/thumbnail-1.webp'),
  videoSrc2: getAssetPath('../../assets/thumbnail-2.webp'),
  videoSrc3: getAssetPath('../../assets/thumbnail-3.webp'),
  videoSrc4: getAssetPath('../../assets/thumbnail-4.webp'),
  videoSrc5: getAssetPath('../../assets/thumbnail-5.webp'),
  videoSrc6: getAssetPath('../../assets/thumbnail-6.webp'),
  chanelImg1: getAssetPath('../../assets/channel-1.jpeg'),
  chanelImg2: getAssetPath('../../assets/channel-2.jpeg'),
  chanelImg3: getAssetPath('../../assets/channel-3.jpeg'),
  chanelImg4: getAssetPath('../../assets/channel-4.jpeg'),
  chanelImg5: getAssetPath('../../assets/channel-5.jpeg'),
  chanelImg6: getAssetPath('../../assets/channel-6.jpeg'),
  hamburger: getAssetPath('../../assets/hamburger-menu.svg'),
  microphone: getAssetPath('../../assets/voice-search-icon.svg'),
  search: getAssetPath('../../assets/search.svg'),
  upload: getAssetPath('../../assets/upload.svg'),
  youtubeLogo: getAssetPath('../../assets/youtube-logo.svg'),
  youtubeApps: getAssetPath('../../assets/youtube-apps.svg'),
  notifications: getAssetPath('../../assets/notifications.svg'),
  mainChannel: getAssetPath('../../assets/my-channel.jpeg'),
  youtubeMusic: getAssetPath('../../assets/youtube-music.svg'),
  library: getAssetPath('../../assets/library.svg'),
  originals: getAssetPath('../../assets/originals.svg'),
  subscriptions: getAssetPath('../../assets/subscriptions.svg'),
  explore: getAssetPath('../../assets/explore.svg'),
  home: getAssetPath('../../assets/home.svg'),
};
